# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SEsyklDbbpfKFAX11sN7rHznY4DmsBVe
"""

# Install necessary libraries
!pip install google-generativeai PyMuPDF

import google.generativeai as genai
import fitz  # PyMuPDF for extracting text from PDFs
from google.colab import files

# Set up Google Gemini API key (Replace with your actual key)
genai.configure(api_key="AIzaSyAWOJSAv_0mOEjuo0GTw_BhdnPAfqxwldM")

# Function to upload a resume (PDF)
def upload_resume():
    print("📂 Please upload your resume (PDF format).")
    uploaded = files.upload()
    for filename in uploaded.keys():
        return filename  # Return the filename of the uploaded resume

# Function to extract text from the uploaded PDF resume
def extract_text_from_pdf(pdf_path):
    text = ""
    with fitz.open(pdf_path) as doc:
        for page in doc:
            text += page.get_text("text") + "\n"
    return text

# Function to analyze resume using Google Gemini AI
def analyze_resume_with_gemini(resume_text, job_desc):
    prompt = f"""
    You are an AI Resume Analyzer. Compare the following resume with the job description and provide:
    - Match percentage
    - Missing skills
    - Suggestions for improvement

    Resume:
    {resume_text}

    Job Description:
    {job_desc}

    Provide a structured response.
    """

    model = genai.GenerativeModel("gemini-pro")
    response = model.generate_content(prompt)

    return response.text  # Extract AI response

# Main function to run the AI Resume Analyzer
def main():
    pdf_filename = upload_resume()
    resume_text = extract_text_from_pdf(pdf_filename)

    # Get Job Description from the User
    job_desc = input("✍️ Enter the Job Description:\n")

    # Analyze the Resume
    print("\n🔍 Analyzing Resume with Google Gemini...\n")
    analysis = analyze_resume_with_gemini(resume_text, job_desc)

    # Show Results
    print("\n📊 AI Analysis Result:\n")
    print(analysis)

# Run the AI Resume Analyzer
main()